### ISSUE TITLE
Missing ToS in the specified version please update to a38a0c7c38fe77f38cf2ae28d982362be08e5864

### ISSUE THREAD

**Issue by philpott** [line/line-conversion-api-server-tag#6]
https://github.com/line/line-conversion-api-server-tag/blob/fd644cca0f8d075ed6f0897d2e97ed572d516a97/metadata.yaml#L4

This line still points at the old template which is why the gallery submission is failing. If you update the sha to point to a38a0c7c38fe77f38cf2ae28d982362be08e5864 the latest template commit that adds the ToS you should be good to submit the template for review.

**Comment by deftfitf** [comment]
@philpott 
Thank you for your feedback. As you said, I will specify the latest version of sha including ToS.
